# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-python
spec:
  selector:
    app: hello-k8s-python
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000